/* eslint-disable */
/** Auto-generated by scripts/sync-repository-catalog.mjs — do not edit by hand. */
export type RepositoryProvider = "github" | "gitlab";

export type CatalogRepository = {
  name: string;
  description?: string;
  url: string;
  provider: RepositoryProvider;
  owner: string;
  isPrivate: boolean;
  isFork: boolean;
};

export type CatalogProjectGroup = {
  id: string;
  title: string;
  tagline?: string;
  repositories: CatalogRepository[];
};

export const repositoryCatalog: CatalogProjectGroup[] = [
  {
    "id": "dev-centr",
    "title": "Dev-Centr",
    "tagline": "Developer environment configuration, tooling, and documentation.",
    "repositories": [
      {
        "name": "agent-rules",
        "description": "Forkable modular agent rules with 1-step assembly for local AI coding assistants.",
        "url": "https://github.com/dev-centr/agent-rules",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antigravity-auto-accept-commands",
        "description": "Cursor extension: status bar toggle to auto-accept Antigravity agent action requests",
        "url": "https://github.com/dev-centr/antigravity-auto-accept-commands",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "centrmark",
        "description": "CentrMark is a new markup language designed to fix the problems with Markdown, MDX, and Asciidoc",
        "url": "https://github.com/dev-centr/centrmark",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "devcentr",
        "description": "A developer center app for configuring dev machines and managing software projects",
        "url": "https://github.com/dev-centr/devcentr",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "devcentr-agent-rules",
        "description": "Rules for Dev-Centr product automation acting on behalf of the user, featuring 1-step assembly.",
        "url": "https://github.com/dev-centr/devcentr-agent-rules",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "devcentr.app",
        "description": "Application homepage and marketing site for Dev-Centr",
        "url": "https://github.com/dev-centr/devcentr.app",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "devcentr.org",
        "description": "Organization landing page for Dev-Centr",
        "url": "https://github.com/dev-centr/devcentr.org",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "docs",
        "description": "Dev-Centr documentation hub. Antora site aggregating dev-centr projects.",
        "url": "https://github.com/dev-centr/docs",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dprint",
        "description": "Pluggable and configurable code formatting platform written in Rust that unifies all your formatters in one tool.",
        "url": "https://github.com/dev-centr/dprint",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "dprint-vscode",
        "description": "Visual Studio Code extension for formatting code with dprint.",
        "url": "https://github.com/dev-centr/dprint-vscode",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "general-knowledge",
        "description": "General developer knowledge: Diátaxis-organized reference, how-tos, and explanations",
        "url": "https://github.com/dev-centr/general-knowledge",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "github-actions-editor",
        "description": "An editor for GitHub Actions",
        "url": "https://github.com/dev-centr/github-actions-editor",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "issue-tracker",
        "description": "Local GitHub issues and comments browser. Syncs issues into SQLite; browse and search with GUI or CLI.",
        "url": "https://github.com/dev-centr/issue-tracker",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "msi-installer-generator",
        "description": "A cross-platform MSI/MSIX generator in D-lang",
        "url": "https://github.com/dev-centr/msi-installer-generator",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "node",
        "description": "Node.js JavaScript runtime ✨🐢🚀✨",
        "url": "https://github.com/dev-centr/node",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "nvm",
        "description": "Node Version Manager - POSIX-compliant bash script to manage multiple active node.js versions",
        "url": "https://github.com/dev-centr/nvm",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "nvm-passthru",
        "description": "Intelligent drop-in nvm-windows passthrough; per-process Node version routing on Windows",
        "url": "https://github.com/dev-centr/nvm-passthru",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "nvm-windows",
        "description": "A node.js version management utility for Windows. Ironically written in Go.",
        "url": "https://github.com/dev-centr/nvm-windows",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "open-folder-with-cursor",
        "description": "Install \"Open-with Cursor\" item in right-click menu in File Explorer in Windows",
        "url": "https://github.com/dev-centr/open-folder-with-cursor",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "packagehub",
        "description": "Publish packages across registries from one dashboard (npm, PyPI, Crates.io)",
        "url": "https://github.com/dev-centr/packagehub",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "prohelp",
        "description": "Progressive & Professional Help CLI Interceptor and Library",
        "url": "https://github.com/dev-centr/prohelp",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "templates",
        "description": "Template settings files for dev tools",
        "url": "https://github.com/dev-centr/templates",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "toolchain-advisor",
        "url": "https://github.com/dev-centr/toolchain-advisor",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "workflow-templates-site",
        "url": "https://github.com/dev-centr/workflow-templates-site",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github",
        "url": "https://github.com/dev-centr/.github",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github-private",
        "url": "https://github.com/dev-centr/.github-private",
        "provider": "github",
        "owner": "dev-centr",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "FoodTruckNerdz",
    "title": "FoodTruckNerdz",
    "tagline": "Food truck discovery platform — web, mobile, and API.",
    "repositories": [
      {
        "name": "developer-portal",
        "description": "3rd party Developer portal",
        "url": "https://github.com/FoodTruckNerdz/developer-portal",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "docs",
        "description": "FTN team's internal documentation",
        "url": "https://github.com/FoodTruckNerdz/docs",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "food-truck-api",
        "description": "Food Truck Zuplo API Gateway",
        "url": "https://github.com/FoodTruckNerdz/food-truck-api",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "ftn-app",
        "description": "Food Truck Nerdz Flutter mobile client",
        "url": "https://github.com/FoodTruckNerdz/ftn-app",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "ftn-site",
        "description": "Food Truck Nerdz Next.js Web App",
        "url": "https://github.com/FoodTruckNerdz/ftn-site",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": true,
        "isFork": true
      },
      {
        "name": "ftn-site-old",
        "description": "(old site) HackaThon 03/07/2025",
        "url": "https://github.com/FoodTruckNerdz/ftn-site-old",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "gitignore-templates",
        "description": "A collection of useful .gitignore templates",
        "url": "https://github.com/FoodTruckNerdz/gitignore-templates",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "help",
        "description": "The Help site and help docs for users",
        "url": "https://github.com/FoodTruckNerdz/help",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "onboarding",
        "description": "Onboarding documentation and Setup GUI to bootstrap dev environment",
        "url": "https://github.com/FoodTruckNerdz/onboarding",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "roadmap",
        "description": "Roadmap site for the public",
        "url": "https://github.com/FoodTruckNerdz/roadmap",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "template",
        "description": "Copy this repository when creating a new repo in FTN",
        "url": "https://github.com/FoodTruckNerdz/template",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github",
        "description": "Public github profile for FTN",
        "url": "https://github.com/FoodTruckNerdz/.github",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github-private",
        "description": "The readme for the Organization's GitHub page",
        "url": "https://github.com/FoodTruckNerdz/.github-private",
        "provider": "github",
        "owner": "FoodTruckNerdz",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "antora-supplemental",
    "title": "Antora Supplemental",
    "tagline": "Themes, workflows, and extensions for Antora documentation sites.",
    "repositories": [
      {
        "name": "antora",
        "description": "A modular documentation site generator that helps you organize and publish content written in AsciiDoc to the web. Ideally suited for users of Asciidoctor.\n\nThis repository hosts the core software components and documentation for Antora.\n\nhttps://antora.org",
        "url": "https://gitlab.com/AMDphreak/antora",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "antora-ai-help-extension",
        "description": "Supplemental Antora content and assets",
        "url": "https://github.com/antora-supplemental/antora-ai-help-extension",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-build-action",
        "description": "GitHub Action to build Antora documentation sites with support for private repos, multi-repo aggregation, and extensions; pair with upload-pages-artifact and deploy-pages for GitHub Pages.",
        "url": "https://github.com/antora-supplemental/antora-build-action",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-dark-theme",
        "description": "Dark UI theme for Antora documentation sites. npm and UI bundle.",
        "url": "https://github.com/antora-supplemental/antora-dark-theme",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-demo",
        "description": "Barebones Antora site demonstrating AsciiDoc features. Samples and templates.",
        "url": "https://github.com/antora-supplemental/antora-demo",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-extensions-registry",
        "description": "Registry and catalog of Antora extensions. antora-extensions.org.",
        "url": "https://github.com/antora-supplemental/antora-extensions-registry",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-github-deploy-template",
        "url": "https://github.com/antora-supplemental/antora-github-deploy-template",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-themes-site",
        "description": "Antora Themes Gallery. User and admin documentation.",
        "url": "https://github.com/antora-supplemental/antora-themes-site",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antora-ui-default",
        "description": "An archetype project that produces a UI for documentation sites created using Antora.\n\nYou can preview this UI at https://antora.gitlab.io/antora-ui-default.",
        "url": "https://gitlab.com/AMDphreak/antora-ui-default",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "antora-workflow-templates",
        "description": "Starter workflow templates for building Antora documentation with GitHub Actions - DIY and reusable action versions with cross-linked explanations",
        "url": "https://github.com/antora-supplemental/antora-workflow-templates",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "architexture-theme-antora",
        "description": "Bespoke architectural theme for Antora documentation",
        "url": "https://github.com/antora-supplemental/architexture-theme-antora",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "asciidoc-interactive",
        "description": "Asciidoctor/Antora extension: interactive instruction flows (JSON5)",
        "url": "https://github.com/antora-supplemental/asciidoc-interactive",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "asciidocdead",
        "description": "Free WYSIWYG AsciiDoc editor",
        "url": "https://github.com/antora-supplemental/asciidocdead",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "asciidoctor",
        "description": ":gem: A fast, open source text processor and publishing toolchain, written in Ruby, for converting AsciiDoc content to HTML 5, DocBook 5, and other formats.",
        "url": "https://github.com/antora-supplemental/asciidoctor",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "asciidoctor-kroki",
        "description": "Asciidoctor.js extension to convert diagrams to images using Kroki!",
        "url": "https://github.com/antora-supplemental/asciidoctor-kroki",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "asciidoctor-opal-node-runtime",
        "description": "⚡️ Opal Runtime specifically designed for Asciidoctor",
        "url": "https://github.com/antora-supplemental/asciidoctor-opal-node-runtime",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "asciidoctor-vscode",
        "description": "AsciiDoc support for Visual Studio Code using Asciidoctor",
        "url": "https://github.com/antora-supplemental/asciidoctor-vscode",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "asciidoctor.js",
        "description": ":scroll: A JavaScript port of Asciidoctor, a modern implementation of AsciiDoc",
        "url": "https://github.com/antora-supplemental/asciidoctor.js",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "docs",
        "description": "Documentation hub for antora-supplemental projects. Antora site with antora-dark-theme.",
        "url": "https://github.com/antora-supplemental/docs",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dprint-plugin-asciidoc",
        "description": "dprint plugin for AsciiDoc. Format .adoc files with dprint (WASM, npm).",
        "url": "https://github.com/antora-supplemental/dprint-plugin-asciidoc",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "jsqu4re_antora_build_fork",
        "description": "A github action to build a antora site",
        "url": "https://github.com/antora-supplemental/jsqu4re_antora_build_fork",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": ".github",
        "url": "https://github.com/antora-supplemental/.github",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github-private",
        "url": "https://github.com/antora-supplemental/.github-private",
        "provider": "github",
        "owner": "antora-supplemental",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "dlang-supplemental",
    "title": "Dlang Supplemental",
    "tagline": "D language libraries, GUI tooling, and documentation.",
    "repositories": [
      {
        "name": "arsd",
        "description": "This is a collection of modules that I've released over the years. Most of them stand alone, or have just one or two dependencies in here, so you don't have to download this whole repo.",
        "url": "https://github.com/dlang-supplemental/arsd",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "asciidoctor-d",
        "description": "Native D implementation of Asciidoctor. Fast AsciiDoc processor.",
        "url": "https://github.com/dlang-supplemental/asciidoctor-d",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "asdf",
        "description": "JSON library",
        "url": "https://github.com/dlang-supplemental/asdf",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "awesome-d",
        "description": "A curated list of awesome D documents, frameworks, libraries and software. Inspired by awesome-python.",
        "url": "https://github.com/dlang-supplemental/awesome-d",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "code-d",
        "description": "Fully featured D language extension for Visual Studio Code using Serve-D",
        "url": "https://github.com/dlang-supplemental/code-d",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "densor",
        "description": "Pure D tensor library and GGUF inference engine. Used by vibe-search-core.",
        "url": "https://github.com/dlang-supplemental/densor",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dlang-custom-dialog",
        "url": "https://github.com/dlang-supplemental/dlang-custom-dialog",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dlang-gui-samples",
        "url": "https://github.com/dlang-supplemental/dlang-gui-samples",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dlang.org",
        "description": "Pages for the dlang.org website, home of the D Programming Language",
        "url": "https://github.com/dlang-supplemental/dlang.org",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "dlangui",
        "description": "Cross Platform GUI for D programming language",
        "url": "https://github.com/dlang-supplemental/dlangui",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "docs",
        "description": "Documentation hub for dlang-supplemental projects. Antora site with antora-dark-theme.",
        "url": "https://github.com/dlang-supplemental/docs",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "fluidsync-daemon",
        "description": "FluidSync GUI daemon with shared memory state and simulated telemetry.",
        "url": "https://github.com/dlang-supplemental/fluidsync-daemon",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "ggwebview",
        "description": "A D lib for create desktop apps with webview",
        "url": "https://github.com/dlang-supplemental/ggwebview",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "graphrag-indexer",
        "url": "https://github.com/dlang-supplemental/graphrag-indexer",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "guino",
        "description": "Unleash guino magic for effortless GUI development in D!",
        "url": "https://github.com/dlang-supplemental/guino",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "json5-dlang",
        "description": "Native JSON5 implementation for Dlang",
        "url": "https://github.com/dlang-supplemental/json5-dlang",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "repo-get",
        "description": "Multi-VCS repository fetch library for D — SDL profiles for git, svn, hg, fossil, and more.",
        "url": "https://github.com/dlang-supplemental/repo-get",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "serve-d",
        "description": "D LSP server (dlang language server protocol server)",
        "url": "https://github.com/dlang-supplemental/serve-d",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "unit-threaded",
        "description": "Advanced unit test framework for D",
        "url": "https://github.com/dlang-supplemental/unit-threaded",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "vector-store-dlang",
        "description": "D-Vector Search. Vector store and embedding utilities in D.",
        "url": "https://github.com/dlang-supplemental/vector-store-dlang",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "vello-d",
        "description": "High-performance, GPU-accelerated 2D vector graphics for Dlang, powered by Vello (Rust)",
        "url": "https://github.com/dlang-supplemental/vello-d",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "vibe-search-core",
        "description": "Vibe Search core. CLIP and search backend in D.",
        "url": "https://github.com/dlang-supplemental/vibe-search-core",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "vibe-search-desktop",
        "description": "Vibe Search desktop client and UI.",
        "url": "https://github.com/dlang-supplemental/vibe-search-desktop",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "webview-d",
        "description": "D binding & wrapper for a tiny cross-platform webview library to build modern cross-platform GUIs.",
        "url": "https://github.com/dlang-supplemental/webview-d",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "webviewd",
        "url": "https://github.com/dlang-supplemental/webviewd",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": ".github",
        "url": "https://github.com/dlang-supplemental/.github",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github-private",
        "url": "https://github.com/dlang-supplemental/.github-private",
        "provider": "github",
        "owner": "dlang-supplemental",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "AMDphreak",
    "title": "AMDphreak",
    "tagline": "Personal repositories across GitHub and GitLab.",
    "repositories": [
      {
        "name": "activity-map-shell",
        "description": "Windows GUI: 2D process/activity map with blocks, launcher, and window thumbnails",
        "url": "https://github.com/AMDphreak/activity-map-shell",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "agent-rules",
        "description": "Modular agent rules with a 1-step assembly preamble for local AI harnesses (Cursor, Antigravity, VSCode).",
        "url": "https://github.com/AMDphreak/agent-rules",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "amazon-giveaway-bot",
        "description": "Bot that automatically enters you in to hundreds of instant amazon giveaways",
        "url": "https://github.com/AMDphreak/amazon-giveaway-bot",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "AMDphreak",
        "url": "https://github.com/AMDphreak/AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "amdphreak.github.io",
        "description": "Developer Profile for AMDphreak",
        "url": "https://github.com/AMDphreak/amdphreak.github.io",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "amdphreak.pages.dev",
        "url": "https://github.com/AMDphreak/amdphreak.pages.dev",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "antigravity-panel",
        "description": "A extension to monitor Google Antigravity IDE quotas & cache usage. Performance dashboard for cloud development.",
        "url": "https://github.com/AMDphreak/antigravity-panel",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "antora-dark-theme",
        "description": "Dark UI theme for Antora documentation sites. npm and UI bundle.",
        "url": "https://github.com/AMDphreak/antora-dark-theme",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "bigrpic.com",
        "description": "Photography studio website for bigrPicture",
        "url": "https://github.com/AMDphreak/bigrpic.com",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "biome-vscode",
        "description": "Biome extension for VS Code",
        "url": "https://github.com/AMDphreak/biome-vscode",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "biomejs-website",
        "description": "Biome's website",
        "url": "https://github.com/AMDphreak/biomejs-website",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "bitwarden-clients",
        "description": "Bitwarden client apps (web, browser extension, desktop, and cli).",
        "url": "https://github.com/AMDphreak/bitwarden-clients",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "BlackJackGame",
        "description": "BlackJack Game with simulated dealer",
        "url": "https://github.com/AMDphreak/BlackJackGame",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "bookmark-cleaner-ai",
        "url": "https://github.com/AMDphreak/bookmark-cleaner-ai",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "chrome-extensions-for-firefox",
        "description": "A Firefox extension that allows you to install and run Chrome extensions by automatically converting their manifests and API calls to Firefox-compatible formats.",
        "url": "https://github.com/AMDphreak/chrome-extensions-for-firefox",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "code-lens",
        "description": "One code snippet, multiple pedagogical lenses — portable JSON5 spec and <code-lens> web component with framework adapters.",
        "url": "https://github.com/AMDphreak/code-lens",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "connectome-filesystem",
        "description": "Modern graph-based flat filesystem",
        "url": "https://github.com/AMDphreak/connectome-filesystem",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "conveyorbelt",
        "description": "Sort DVDs and other media discs into bins/chutes along a conveyor belt\r\nRequired components:\r\n-Raspberry Pi 3\r\n-Rotary Encoder\r\n-Zebra Scanner\r\n-Python 3.7",
        "url": "https://gitlab.com/AMDphreak/conveyorbelt",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "CookSystems-FastTrackD-Assignments",
        "description": "Cook Systems FastTrack'D Java developer training program in Memphis, TN. These are my assignments from that bootcamp.",
        "url": "https://github.com/AMDphreak/CookSystems-FastTrackD-Assignments",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "corepack",
        "description": "Package manager version manager for Node.js projects",
        "url": "https://github.com/AMDphreak/corepack",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "create-tauri-app",
        "description": "Rapidly scaffold out a new tauri app project.",
        "url": "https://github.com/AMDphreak/create-tauri-app",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "CrystalDiskMark",
        "description": "CrystalDiskMark",
        "url": "https://github.com/AMDphreak/CrystalDiskMark",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "crystaldiskmark-dlang",
        "description": "CrystalDiskMark rewrite in Dlang",
        "url": "https://github.com/AMDphreak/crystaldiskmark-dlang",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "cyberpanel-uninstaller",
        "description": "unofficial uninstaller/s for CyberPanel since the company is too lazy to make one themselves",
        "url": "https://github.com/AMDphreak/cyberpanel-uninstaller",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "d-warden",
        "url": "https://github.com/AMDphreak/d-warden",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dart-playbox",
        "description": "Dart language testing",
        "url": "https://github.com/AMDphreak/dart-playbox",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dart-sdk",
        "description": "The Dart SDK, including the VM, dart2js, core libraries, and more.",
        "url": "https://github.com/AMDphreak/dart-sdk",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Desktop-Assistant-AI",
        "description": "An AI to help users when they don't know what to do, with emphasis on code help",
        "url": "https://github.com/AMDphreak/Desktop-Assistant-AI",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dotfile-template",
        "description": "template for dotfiles for all programming. Such as .env files that contain secrets on local machine",
        "url": "https://github.com/AMDphreak/dotfile-template",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "dsam-christmas-2025-preview",
        "description": "dsam 2025 christmas party capture one preview",
        "url": "https://github.com/AMDphreak/dsam-christmas-2025-preview",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "dsam-christmas-2025-preview",
        "url": "https://gitlab.com/AMDphreak/dsam-christmas-2025-preview",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "dsam-christmas-2025-preview-broken",
        "url": "https://gitlab.com/AMDphreak/dsam-christmas-2025-preview-broken",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "DSAM-OCR-Research",
        "description": "Research into Optical Character Recognition for DSAM",
        "url": "https://github.com/AMDphreak/DSAM-OCR-Research",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "dsam-resources",
        "description": "DSAM's resources directory for families with special needs",
        "url": "https://github.com/AMDphreak/dsam-resources",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "electron-custom-dialog",
        "url": "https://github.com/AMDphreak/electron-custom-dialog",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "equivalence-engine",
        "description": "High-performance, D-based transformation engine for modular codebase adaptation and version evolution.",
        "url": "https://github.com/AMDphreak/equivalence-engine",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "equivalence-engine-action",
        "description": "Modular GitHub Action to automate codebase adaptation using the Evolution Engine and custom rulesets.",
        "url": "https://github.com/AMDphreak/equivalence-engine-action",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "evolution-rules-code",
        "description": "Standard SDL rulesets for adapting Qt 5.x codebases to Qt 6.x with Evolution Engine",
        "url": "https://github.com/AMDphreak/evolution-rules-code",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "evolution-rules-filesystem",
        "description": "Cross-OS filesystem path equivalency rules (Linux, Windows, macOS, BSD) for the Evolution Engine.",
        "url": "https://github.com/AMDphreak/evolution-rules-filesystem",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "explorer-refresh-thumbcache",
        "description": "Windows 11 Explorer context menu: refresh thumbnail cache (D/LDC, -nogc)",
        "url": "https://github.com/AMDphreak/explorer-refresh-thumbcache",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "fixnow-dev",
        "url": "https://github.com/AMDphreak/fixnow-dev",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "ftn-site",
        "description": "Food Truck Nerdz Next.js Web App",
        "url": "https://github.com/AMDphreak/ftn-site",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": true
      },
      {
        "name": "git-gud.info",
        "url": "https://github.com/AMDphreak/git-gud.info",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "git-scm.com",
        "description": "The git-scm.com website. Note that this repository is only for the website; issues with git itself should go to https://git-scm.com/community.",
        "url": "https://github.com/AMDphreak/git-scm.com",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "git-un",
        "description": "git-unfuckified - A more intuitive Git CLI with improved syntax and user experience",
        "url": "https://github.com/AMDphreak/git-un",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "github-docs",
        "description": "The open-source repo for docs.github.com",
        "url": "https://github.com/AMDphreak/github-docs",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Gittyup",
        "description": "Understand your Git history!",
        "url": "https://github.com/AMDphreak/Gittyup",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "google-docs-asciidoc-markdown-converter",
        "url": "https://github.com/AMDphreak/google-docs-asciidoc-markdown-converter",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "gso-site",
        "description": "Website for Germantown Symphony Orchestra built with Astro, SolidJS, and Netlify",
        "url": "https://github.com/AMDphreak/gso-site",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "Haskell-Programming-from-Beginner-to-Expert",
        "description": "A book for beginners in computer programming around age 10. Readers advance from beginner to expert. The book teaches a college level understanding of the topics.",
        "url": "https://gitlab.com/AMDphreak/Haskell-Programming-from-Beginner-to-Expert",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "hello-haskell",
        "description": "Hello World Haskell",
        "url": "https://gitlab.com/AMDphreak/hello-haskell",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "homebrew-tap",
        "description": "Homebrew tap for AMDphreak projects",
        "url": "https://github.com/AMDphreak/homebrew-tap",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "hydrus",
        "description": "A personal booru-style media tagger that can import files and tags from your hard drive and popular websites. Content can be shared with other users via user-run servers.",
        "url": "https://github.com/AMDphreak/hydrus",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "iup",
        "description": "iup wrapper for Nim. Used to be part of the stdlib, now a Nimble package.",
        "url": "https://github.com/AMDphreak/iup",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "java-assignment-collections-AMDphreak",
        "url": "https://github.com/AMDphreak/java-assignment-collections-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "java-assignment-fibonacci-fizzbuzz-AMDphreak",
        "url": "https://github.com/AMDphreak/java-assignment-fibonacci-fizzbuzz-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "java-assignment-rationals-AMDphreak",
        "url": "https://github.com/AMDphreak/java-assignment-rationals-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "java-assignment-schema-design-AMDphreak",
        "url": "https://github.com/AMDphreak/java-assignment-schema-design-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "javascript-beginner-demo",
        "description": "Beginner Javascript demo. The most basic demonstration of Javascript's ability to log output behind the scenes and update the HTML DOM",
        "url": "https://github.com/AMDphreak/javascript-beginner-demo",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "Job-Search-Analyzer",
        "description": "An Email analyzer to produce reports about my job applications and rejections",
        "url": "https://github.com/AMDphreak/Job-Search-Analyzer",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "js-assessment-dev-duel-AMDphreak",
        "url": "https://github.com/AMDphreak/js-assessment-dev-duel-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "js-assignment-copy-page-AMDphreak",
        "url": "https://github.com/AMDphreak/js-assignment-copy-page-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "js-assignment-declarative-AMDphreak",
        "url": "https://github.com/AMDphreak/js-assignment-declarative-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "js-assignment-primer-AMDphreak",
        "url": "https://github.com/AMDphreak/js-assignment-primer-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "js-assignment-quizler-AMDphreak",
        "url": "https://github.com/AMDphreak/js-assignment-quizler-AMDphreak",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "jsonviewer",
        "description": "JSON Viewer is a jolly good JSON Viewer",
        "url": "https://github.com/AMDphreak/jsonviewer",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "krita",
        "description": "Krita is a free and open source cross-platform application that offers an end-to-end solution for creating digital art files from scratch built on the KDE and Qt frameworks.",
        "url": "https://github.com/AMDphreak/krita",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "krita-ai-diffusion",
        "description": "Streamlined interface for generating images with AI in Krita. Inpaint and outpaint with optional text prompt, no tweaking required.",
        "url": "https://github.com/AMDphreak/krita-ai-diffusion",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "learn-racket",
        "url": "https://gitlab.com/AMDphreak/learn-racket",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "LearnMeAHaskell",
        "description": "Lessons from the Learn You a Haskell tutorial",
        "url": "https://github.com/AMDphreak/LearnMeAHaskell",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "lemonadestand",
        "url": "https://github.com/AMDphreak/lemonadestand",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "libequivalence",
        "description": "D library: rule engine for the Equivalence Engine",
        "url": "https://github.com/AMDphreak/libequivalence",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "llama.cpp",
        "description": "LLM inference in C/C++",
        "url": "https://github.com/AMDphreak/llama.cpp",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "lol-riot-d",
        "description": "D: Riot Web API + LCU (lol-riot-d)",
        "url": "https://github.com/AMDphreak/lol-riot-d",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "MDN-content",
        "description": "The content behind MDN Web Docs",
        "url": "https://github.com/AMDphreak/MDN-content",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "mkeditor",
        "description": "MKEditor - Markdown with style.",
        "url": "https://github.com/AMDphreak/mkeditor",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "multimux",
        "description": "Multichannel audio mixdown tool for video files powered by ffmpeg",
        "url": "https://github.com/AMDphreak/multimux",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "nextjs-sampleproject",
        "url": "https://github.com/AMDphreak/nextjs-sampleproject",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "nikon-camera-bridge",
        "description": "Webcam Bridge for Nikon: use your Nikon USB webcam in Zoom, Teams, or OBS as a virtual camera, with HTTP control for focus and exposure. Windows first, open source.",
        "url": "https://github.com/AMDphreak/nikon-camera-bridge",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "obs-backgroundremoval",
        "description": "An OBS plugin for removing background in portrait images (video), making it easy to replace the background when screen recording.",
        "url": "https://github.com/AMDphreak/obs-backgroundremoval",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "obs-studio",
        "description": "OBS - Free and open source software for live streaming and screen recording",
        "url": "https://github.com/AMDphreak/obs-studio",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "OpenSSH-GUI",
        "description": "A simple GUI front-end for OpenSSH for Windows, Linux and Mac!",
        "url": "https://github.com/AMDphreak/OpenSSH-GUI",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "orbris",
        "url": "https://github.com/AMDphreak/orbris",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "packet-x-ing",
        "description": "A packet sniffer and attacking tool written in Racket-Lisp",
        "url": "https://gitlab.com/AMDphreak/packet-x-ing",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "personal-records-vault",
        "description": "Personal Records Vault: desktop app, browser extension, TypeScript SDK, and static web vault shell.",
        "url": "https://github.com/AMDphreak/personal-records-vault",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "pnpm",
        "description": "Fast, disk space efficient package manager",
        "url": "https://github.com/AMDphreak/pnpm",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "PowerShell",
        "description": "PowerShell for every system!",
        "url": "https://github.com/AMDphreak/PowerShell",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "pwa-starter",
        "url": "https://github.com/AMDphreak/pwa-starter",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "racket",
        "description": "The Racket repository",
        "url": "https://github.com/AMDphreak/racket",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Roo-Code",
        "description": "Roo Code (prev. Roo Cline) gives you a whole dev team of AI agents in your code editor.",
        "url": "https://github.com/AMDphreak/Roo-Code",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Rust-lang-book",
        "description": "The Rust Programming Language",
        "url": "https://github.com/AMDphreak/Rust-lang-book",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Schedulinator",
        "description": "Classroom Scheduler / Asset Scheduler",
        "url": "https://github.com/AMDphreak/Schedulinator",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "scribe",
        "description": "Edit Markdown/AsciiDoc in GitHub static site repos — for non-technical users",
        "url": "https://github.com/AMDphreak/scribe",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "site-downloader",
        "description": "Comprehensive toolset for downloading and archiving websites to static, offline copies.",
        "url": "https://github.com/AMDphreak/site-downloader",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "solid-ui",
        "description": "Beautifully designed components. Built with Kobalte & corvu. Styled with Tailwind CSS.",
        "url": "https://github.com/AMDphreak/solid-ui",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "spacedrive",
        "description": "Spacedrive is an open source cross-platform file explorer, powered by a virtual distributed filesystem written in Rust.",
        "url": "https://github.com/AMDphreak/spacedrive",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "spring-assessment-social-media-teamblue",
        "url": "https://github.com/AMDphreak/spring-assessment-social-media-teamblue",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "storganizer",
        "description": "Store Inventory Tracker",
        "url": "https://gitlab.com/AMDphreak/storganizer",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "svg-explorer-extension",
        "description": "Extension module for Windows Explorer to render SVG thumbnails, so that you can have an overview of your SVG files",
        "url": "https://github.com/AMDphreak/svg-explorer-extension",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "svgesus",
        "description": "Windows SVG thumbnail shell extension (SVG Jesus). D + NanoSVG.",
        "url": "https://github.com/AMDphreak/svgesus",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "SyncthingWindowsSetup",
        "description": "Syncthing Windows Setup",
        "url": "https://github.com/AMDphreak/SyncthingWindowsSetup",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "tcp-server",
        "description": "Creates a server that waits for TCP packets.",
        "url": "https://gitlab.com/AMDphreak/tcp-server",
        "provider": "gitlab",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "transcoder-suite",
        "description": "Modular, playbook-driven video transcoding system for PowerShell 7. Optimized for high-quality archival and batch processing.",
        "url": "https://github.com/AMDphreak/transcoder-suite",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "typst",
        "description": "A markup-based typesetting system that is powerful and easy to learn.",
        "url": "https://github.com/AMDphreak/typst",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "UniGetUI",
        "description": "UniGetUI: The Graphical Interface for your package managers. Could be terribly described as a package manager manager to manage your package managers",
        "url": "https://github.com/AMDphreak/UniGetUI",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "usersettings",
        "description": "Portable Local Settings Storage for Python",
        "url": "https://github.com/AMDphreak/usersettings",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "vello",
        "description": "A GPU compute-centric 2D renderer.",
        "url": "https://github.com/AMDphreak/vello",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "ver",
        "description": "Universal Version Control Interface - Pluggable system for Git, SVN, and other VCS providers with intuitive syntax",
        "url": "https://github.com/AMDphreak/ver",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "vercel-mcp-overview",
        "description": "Public overview of Vercel's MCP server for the github.com/mcp directory. Full documentation at https://vercel.com/docs/mcp/vercel-mcp",
        "url": "https://github.com/AMDphreak/vercel-mcp-overview",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Virtualization-Documentation",
        "description": "Place to store our documentation, code samples, etc for public consumption.",
        "url": "https://github.com/AMDphreak/Virtualization-Documentation",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "vscode",
        "description": "Visual Studio Code",
        "url": "https://github.com/AMDphreak/vscode",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "vscode-markdown",
        "description": "Markdown All in One",
        "url": "https://github.com/AMDphreak/vscode-markdown",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "vscode-uncrustify",
        "description": "Uncrustify code formatter extension for Visual Studio Code",
        "url": "https://github.com/AMDphreak/vscode-uncrustify",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "whisper.cpp",
        "description": "Port of OpenAI's Whisper model in C/C++",
        "url": "https://github.com/AMDphreak/whisper.cpp",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "wiki-docs",
        "description": "Docs for Wiki.js 2.x",
        "url": "https://github.com/AMDphreak/wiki-docs",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "Windows-Theme-Autochanger",
        "description": "Dark mode auto-changer for Windows 11 at night",
        "url": "https://github.com/AMDphreak/Windows-Theme-Autochanger",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "winget-cli",
        "description": "WinGet is the Windows Package Manager. This project includes a CLI (Command Line Interface), PowerShell modules, and a COM (Component Object Model) API (Application Programming Interface).",
        "url": "https://github.com/AMDphreak/winget-cli",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "winget-github-autopackage-instructions",
        "description": "Winget GitHub Autopackage Pipeline Setup Instructions",
        "url": "https://github.com/AMDphreak/winget-github-autopackage-instructions",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "winget-pkgs",
        "description": "The Microsoft community Windows Package Manager manifest repository",
        "url": "https://github.com/AMDphreak/winget-pkgs",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "xi-editor",
        "description": "A modern editor with a backend written in Rust.",
        "url": "https://github.com/AMDphreak/xi-editor",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "zed",
        "description": "Code at the speed of thought – Zed is a high-performance, multiplayer code editor from the creators of Atom and Tree-sitter.",
        "url": "https://github.com/AMDphreak/zed",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": "zed-extensions",
        "description": "Extensions for the Zed editor",
        "url": "https://github.com/AMDphreak/zed-extensions",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": true
      },
      {
        "name": ".issues",
        "description": "Screenshots uploaded by AI for inclusion in GitHub issues",
        "url": "https://github.com/AMDphreak/.issues",
        "provider": "github",
        "owner": "AMDphreak",
        "isPrivate": false,
        "isFork": false
      }
    ]
  },
  {
    "id": "formatte",
    "title": "formatte",
    "tagline": "Formatting tooling organization.",
    "repositories": [
      {
        "name": ".github",
        "description": "Organization profile and community health files",
        "url": "https://github.com/formatte/.github",
        "provider": "github",
        "owner": "formatte",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github-private",
        "description": "Members-only org files",
        "url": "https://github.com/formatte/.github-private",
        "provider": "github",
        "owner": "formatte",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "openshellorg",
    "title": "Open Shell Org",
    "tagline": "Open Shell community.",
    "repositories": [
      {
        "name": "open-shell-org",
        "url": "https://github.com/openshellorg/open-shell-org",
        "provider": "github",
        "owner": "openshellorg",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": ".github",
        "url": "https://github.com/openshellorg/.github",
        "provider": "github",
        "owner": "openshellorg",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "Linx-Photos",
    "title": "Linx Photos",
    "tagline": "Photo service and documentation.",
    "repositories": [
      {
        "name": "docs.linx.photos",
        "url": "https://github.com/Linx-Photos/docs.linx.photos",
        "provider": "github",
        "owner": "Linx-Photos",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "photo-service",
        "url": "https://github.com/Linx-Photos/photo-service",
        "provider": "github",
        "owner": "Linx-Photos",
        "isPrivate": true,
        "isFork": false
      }
    ]
  },
  {
    "id": "memphis-cs-projects",
    "title": "Memphis CS Projects",
    "tagline": "University coursework and team projects.",
    "repositories": [
      {
        "name": "Bharat",
        "description": "iHunt (Idea Hunt)",
        "url": "https://github.com/memphis-cs-projects/Bharat",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "Foodee",
        "url": "https://github.com/memphis-cs-projects/Foodee",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "indigo-s24",
        "url": "https://github.com/memphis-cs-projects/indigo-s24",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "mjac-f23",
        "url": "https://github.com/memphis-cs-projects/mjac-f23",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "purple-f23",
        "url": "https://github.com/memphis-cs-projects/purple-f23",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": false,
        "isFork": false
      },
      {
        "name": "Team-PSYC100",
        "url": "https://github.com/memphis-cs-projects/Team-PSYC100",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": true,
        "isFork": false
      },
      {
        "name": "tomato-s24",
        "url": "https://github.com/memphis-cs-projects/tomato-s24",
        "provider": "github",
        "owner": "memphis-cs-projects",
        "isPrivate": false,
        "isFork": false
      }
    ]
  }
];

export const catalogGeneratedAt = "2026-05-30";

export function catalogRepoCount(): number {
  return repositoryCatalog.reduce((n, g) => n + g.repositories.length, 0);
}
